version: '3'

services:
  rabbitmq:
    image: "rabbitmq:management-alpine"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - '5552:5552' # RabbitMQ stream port
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # Management console